# Site settings
title: F4 Developer
description: "F4 Developer (Stanisław Kowański). Web development, WordPress development, Minecraft plugins, setup and administration of your web services. Full-stack. You are very welcome!"
baseurl: ""
url: "https://www.f4dev.me"

# User settings
username: Stanislaw Kowanski
user_title: F4 Developer (Stanisław Kowański)
email: root@f4dev.me
github_username: kovansky
profile_picture: https://www.f4dev.me/logo.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: Start
      url: /
      key_trigger: 1
    - title: About me
      url: /about
      key_trigger: 2
    - title: Portfolio
      url: /portfolio
      key_trigger: 3
    - title: Offer
      url: /offer
      key_trigger: 4
  section_2:
    - title: GitHub
      url: http://www.github.com/kovansky
      key_trigger: g
    - title: Search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: D&D Encounter Calculator
    url: /dde
    image: /assets/img/portfolio/dde.png
    tags:
      - GO
      - Desktop
  - name: Qubatura — design and art
    url: /qubatura
    image: /assets/img/portfolio/Qubatura.png
    tags:
      - Web
      - WordPress
  - name: Piaseczno Scout District
    url: /zhppiaseczno
    image: /assets/img/portfolio/zhppiaseczno.png
    tags:
      - Web
      - WordPress
  - name: PluginController
    url: /plugincontroller
    image: /assets/img/portfolio/PluginController.png
    tags:
      - Java
  - name: RobRoyArt
    url: /robroyart
    image: /assets/img/portfolio/robroyart.png
    tags:
      - Web
  - name: MCTraps Shop
    url: /mctrapsshop
    image: /assets/img/portfolio/mctraps-shop.png
    tags:
      - Java
  - name: MCTraps HelpOp
    url: /mctrapshelpop
    image: /assets/img/portfolio/mctraps-helpop.png
    tags:
      - Java

langs:
  - Java
  - GO
  - Web
  - Desktop
  - WordPress

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
